name: Generate ASCII Artwork

on: push

jobs:
    first_job-1:
        runs-on: ubuntu-latest
        steps:
            - name: Checkout code
              uses: actions/checkout@v4
            
            - name: Create Directory and Add Files
              run: |
                mkdir -p build
                echo "Hello, WelComeee!" > build/index.html
            
            - name: List repo files
              run: ls -ltra

            - name: cat the index file
              run: cat build/index.html
            
            - name: Copy To Server
              uses: appleboy/scp-action@master
              with:
                host: ${{ vars.IIS_HOST_DATA }}
                username: ${{ vars.IIS_USERNAME_DATA }}
                password: ${{ secrets.IIS_PASSWORD_DATA }}
                source: "build/*"
                target: C:\inetpub\wwwroot\