name: Generate ASCII Artwork with multiple jobs

on: push

jobs:
    build-job-1:
        runs-on: ubuntu-latest
        steps:
           
            - name: Install cowsay program
              run: sudo apt-get install cowsay
            
            - name: Execute cowsay cmd
              run: cowsay -f dragon "Run for cover, I am a DRAGON RAWR" >> dragon.txt

            - name: Upload artifact
              uses: actions/upload-artifact@v4
              with:
                name: my-artifact
                path: dragon.txt

    test-job-2:
        needs: build-job-1
        runs-on: ubuntu-latest
        steps:

            - name: Download artifact
              uses: actions/download-artifact@v4
              with:
                name: my-artifact

            - name: Test file exists
              run: grep -i "dragon" dragon.txt

    deploy-job-3:
        runs-on: ubuntu-latest
        steps:

            - name: Download artifact
              uses: actions/download-artifact@v4
              with:
                name: my-artifact
        
            - name: Read files
              run: cat dragon.txt
            
            - name: Deploy
              run: echo "Deployingggggggggggggggg"
              